/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data30 struct {
	Id string `json:"id"`
	CustomerId string `json:"customer_id"`
	OrganisationId string `json:"organisation_id"`
	Environment string `json:"environment"`
	Type_ string `json:"type"`
	Name string `json:"name"`
	Currency string `json:"currency"`
	Balance int32 `json:"balance"`
	Brand string `json:"brand"`
	Status string `json:"status"`
	BillingAddress *AllOfData30BillingAddress `json:"billing_address"`
	ExpiryMonth string `json:"expiry_month"`
	ExpiryYear string `json:"expiry_year"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
