/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfGetAccountbyidData struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Bvn string `json:"bvn"`
	KycTier string `json:"kyc_tier"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DeletedAt string `json:"deleted_at"`
	Status string `json:"status"`
	Environment string `json:"environment"`
	OrganizationId string `json:"organization_id"`
	Balance int32 `json:"balance"`
	Currency string `json:"currency"`
	Frequency int32 `json:"frequency"`
	FrequencyCount int32 `json:"frequency_count"`
	MetaData *interface{} `json:"meta_data"`
	CustomerId string `json:"customer_id"`
	Customer *Object `json:"customer"`
	AccountNumber string `json:"account_number"`
	BankName string `json:"bank_name"`
	Type_ string `json:"type"`
	CollectionAccount bool `json:"collection_account"`
	HideAccount bool `json:"hide_account"`
	SkipNumber bool `json:"SkipNumber"`
	ExternalAccount *interface{} `json:"external_account"`
	Alias string `json:"alias"`
}
