/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfData12Meta struct {
	Currency string `json:"currency"`
	MaximumFee string `json:"maximum_fee,omitempty"`
	MinimumFee string `json:"minimum_fee,omitempty"`
	DataExpiry string `json:"data_expiry,omitempty"`
	DataValue string `json:"data_value,omitempty"`
	Fee string `json:"fee,omitempty"`
}
