/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Meta2 struct {
	BusinessUnit string `json:"business_unit"`
	LastTransactionDate string `json:"last_transaction_date"`
	Undertaking string `json:"undertaking"`
}
