/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data55 struct {
	Id string `json:"id"`
	Count int32 `json:"count"`
	TotalAmount int32 `json:"total_amount"`
	Status string `json:"status"`
}
