/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfIssueCardData struct {
	Id string `json:"id"`
	AccountId string `json:"account_id"`
	CustomerId string `json:"customer_id"`
	OrganisationId string `json:"organisation_id"`
	Environment string `json:"environment"`
	Type_ string `json:"type"`
	Name string `json:"name"`
	Currency string `json:"currency"`
	ProviderCardId string `json:"provider_card_id"`
	ProviderCardHolderId string `json:"provider_card_holder_id"`
	Brand string `json:"brand"`
	Status string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	KycDetail *Object `json:"kyc_detail"`
	BillingAddress *Object `json:"billing_address"`
	SpendingChannels *Object `json:"spending_channels"`
}
