/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Meta3 struct {
	Debt int32 `json:"debt"`
	DebtDeduction string `json:"debt_deduction"`
	MeterType string `json:"meter_type"`
}
