/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type MakePaymentRequest struct {
	Amount int32 `json:"amount"`
	ProductId string `json:"product_id"`
	OperatorId string `json:"operator_id"`
	DeviceDetails *AllOfMakePaymentRequestDeviceDetails `json:"device_details"`
}
