/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data61 struct {
	Amount string `json:"amount"`
	Created string `json:"created"`
	AccountNumber string `json:"account_number"`
	Address string `json:"address"`
	BusinessUnit string `json:"business_unit"`
	CurrentDebt string `json:"current_debt"`
	CustomerCategory string `json:"customer_category"`
	EReceipt string `json:"e_receipt"`
	Meta *AllOfData61Meta `json:"meta"`
	MeterNumber string `json:"meter_number"`
	Name string `json:"name"`
	Operator string `json:"operator"`
	OperatorReceipt string `json:"operator_receipt"`
	OperatorReference string `json:"operator_reference"`
	OperatorVat string `json:"operator_vat"`
	Payer *AllOfData61Payer `json:"payer"`
	PaymentReference string `json:"payment_reference"`
	PreviousDebt string `json:"previous_debt"`
	Status string `json:"status"`
	TariffClass string `json:"tariff_class"`
	TariffRate string `json:"tariff_rate"`
	Token string `json:"token"`
	TokenCost string `json:"token_cost"`
	Units string `json:"units"`
}
