/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type TransfersBody struct {
	Amount int32 `json:"amount"`
	BankCode string `json:"bank_code"`
	AccountNumber string `json:"account_number"`
	AccountId string `json:"account_id"`
	Narration string `json:"narration"`
	Reference string `json:"reference"`
	MetaData *interface{} `json:"meta_data"`
}
