/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfData25KycDetail struct {
	Dob string `json:"dob"`
	IdentityType string `json:"identity_type"`
	IdentityNumber string `json:"identity_number"`
	Email string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}
