/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type MakePaymentRequest1 struct {
	Amount int32 `json:"amount"`
	ProductId string `json:"product_id"`
	OperatorId string `json:"operator_id"`
	BeneficiaryMsisdn string `json:"beneficiary_msisdn"`
	AccountId string `json:"account_id"`
}
