/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfUpgradedCustomerT3Data struct {
	Id string `json:"id"`
	FullName string `json:"full_name"`
	PhoneNumber string `json:"phone_number"`
	OrganizationId string `json:"organization_id"`
	Environment string `json:"environment"`
	Email string `json:"email"`
	Country string `json:"country"`
	Group string `json:"group"`
	Status string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	SyncData *Object `json:"SyncData"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	KycTier string `json:"kyc_tier"`
	Bvn string `json:"bvn"`
	PlaceOfBirth string `json:"place_of_birth"`
	Gender string `json:"gender"`
	IdentityUrl string `json:"identity_url"`
	ImageUrl string `json:"image_url"`
	MeansOfIdentity string `json:"means_of_identity"`
	DateOfBirth string `json:"date_of_birth"`
	MeansOfIdentityUrl string `json:"means_of_identity_url"`
	CustomerType string `json:"customer_type"`
	Source string `json:"source"`
	Address *Object `json:"address"`
}
