/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Customer11 struct {
	Success bool `json:"success"`
	Data *AllOfCustomer11Data `json:"data"`
	Message string `json:"message"`
}
