/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data1 struct {
	Id string `json:"id"`
	Name string `json:"name"`
	CreatedAt string `json:"created_at"`
	AccountNumber string `json:"account_number"`
	BankName string `json:"bank_name"`
}
