/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type MetaData102 struct {
	CardNumber string `json:"card_number,omitempty"`
	ReceiverPhoneNumber string `json:"receiver_phone_number,omitempty"`
}
