/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type DeviceDetails struct {
	MeterType string `json:"meter_type,omitempty"`
	DeviceNumber string `json:"device_number,omitempty"`
	BeneficiaryMsisdn string `json:"beneficiary_msisdn,omitempty"`
}
