/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data13 struct {
	Address string `json:"address"`
	Email string `json:"email"`
	Name string `json:"name"`
	Phone string `json:"phone"`
	PaymentReference string `json:"payment_reference"`
}
