/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfCustomervalidationData struct {
	AccountNumber string `json:"account_number"`
	Address string `json:"address"`
	Category string `json:"category"`
	Debt string `json:"debt"`
	Email string `json:"email"`
	Meta *Object `json:"meta"`
	MeterNumber string `json:"meter_number"`
	MinimumPayable string `json:"minimum_payable"`
	Name string `json:"name"`
	PaymentReference string `json:"payment_reference"`
	Phone string `json:"phone"`
	TariffClass string `json:"tariff_class"`
	TariffRate string `json:"tariff_rate"`
	UniqueId string `json:"unique_id"`
}
