/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type OrganizationCustomers struct {
	Success bool `json:"success"`
	Data []Data44 `json:"data"`
	Message string `json:"message"`
	Metadata *AllOfOrganizationCustomersMetadata `json:"metadata"`
}
