/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data6 struct {
	Id string `json:"id"`
	Type_ string `json:"type"`
	Number string `json:"number"`
	Balance int32 `json:"balance"`
	Bank string `json:"bank"`
}
