/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Data7 struct {
	Desc string `json:"desc"`
	Id string `json:"id"`
	Name string `json:"name"`
	Sector string `json:"sector"`
}
