/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfTelcoPaymentMadeData struct {
	Amount string `json:"amount"`
	Created string `json:"created"`
	CustomerCategory string `json:"customer_category"`
	EReceipt string `json:"e_receipt"`
	Meta *Object `json:"meta"`
	Operator string `json:"operator"`
	OperatorReceipt string `json:"operator_receipt"`
	OperatorReference string `json:"operator_reference"`
	Payer *Object `json:"payer"`
	PaymentReference string `json:"payment_reference"`
	Status string `json:"status"`
}
