/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type CustomerDetail struct {
	FullName string `json:"full_name"`
	PhoneNumber string `json:"phone_number"`
	Country string `json:"country"`
	Email string `json:"email,omitempty"`
}
