/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type AllOfData26BillingAddress struct {
	City string `json:"city"`
	State string `json:"state"`
	Country string `json:"country"`
	Street string `json:"street,omitempty"`
	PostalCode string `json:"postal_code,omitempty"`
}
