/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type Meta5 struct {
	AuditNumber string `json:"audit_number"`
	ConfirmationCode string `json:"confirmation_code"`
}
