/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type CustomersCustomerIdBody struct {
	Email string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	CustomerType string `json:"customer_type"`
}
