/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type ChangeCardPinRequest struct {
	OldPin string `json:"old_pin"`
	NewPin string `json:"new_pin"`
}
