/*
 * Bloc API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bloc

type T1CustomerIdBody struct {
	PlaceOfBirth string `json:"place_of_birth"`
	Dob string `json:"dob"`
	Gender string `json:"gender"`
	Country string `json:"country"`
	Address *Object `json:"address"`
	Image string `json:"image"`
}
